# Generated by Django 5.2.9 on 2025-12-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("announcement", "Announcement"),
                    ("report", "Report Feedback"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="content",
            field=models.TextField(
                help_text="Placeholders: {student_name}, {class_name}, {school_name}, {date}, {position}, {average}, {conduct}, {attendance}, {term}, {remark}"
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("announcement", "Announcement"),
                    ("report", "Report Feedback"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
