# Generated by Django 5.2.9 on 2025-12-31 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_alter_smsmessage_message_type_and_more"),
        ("students", "0003_student_guardian_relationship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["created_at"], name="communicati_created_20e7ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["status"], name="communicati_status_b2252b_idx"),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["created_at", "status"], name="communicati_created_656e33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["message_type"], name="communicati_message_18a684_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["recipient_phone"], name="communicati_recipie_96a338_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smstemplate",
            index=models.Index(
                fields=["message_type", "is_active"],
                name="communicati_message_48b83f_idx",
            ),
        ),
    ]
