# Generated by Django 5.2.9 on 2026-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_add_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("announcement", "Announcement"),
                    ("report", "Report Feedback"),
                    ("exeat", "Exeat Notification"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("announcement", "Announcement"),
                    ("report", "Report Feedback"),
                    ("exeat", "Exeat Notification"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
