# Generated by Django 5.2.9 on 2026-02-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_add_exeat_sms_tracking"),
        ("teachers", "0010_remove_redundant_db_index_on_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("announcement", "Announcement"),
                    ("report", "Report Feedback"),
                    ("exeat", "Exeat Notification"),
                    ("staff", "Staff Message"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("attendance", "Attendance Alert"),
                    ("fee", "Fee Reminder"),
                    ("announcement", "Announcement"),
                    ("report", "Report Feedback"),
                    ("exeat", "Exeat Notification"),
                    ("staff", "Staff Message"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("staff", "Staff Message"),
                            ("announcement", "Announcement"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_messages",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="communicati_created_0d1c9e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="communicati_status_ea7c14_idx"
                    ),
                    models.Index(
                        fields=["created_at", "status"],
                        name="communicati_created_a568f1_idx",
                    ),
                    models.Index(
                        fields=["message_type"], name="communicati_message_ae87c4_idx"
                    ),
                ],
            },
        ),
    ]
