# Generated by Django 5.2.9 on 2026-02-24 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_announcement_announcementread_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="announcement",
            name="communicati_target__6ff56b_idx",
        ),
        migrations.AddField(
            model_name="announcement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("parents", "Parents"),
                    ("students", "Students"),
                ],
                default="staff",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="scope",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("teaching", "Teaching Staff"),
                    ("non_teaching", "Non-Teaching Staff"),
                    ("level", "By Level"),
                    ("class", "By Class"),
                    ("individual", "Individual"),
                ],
                default="all",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="scope_detail",
            field=models.CharField(
                blank=True,
                help_text="Class PK, level_type:number, or comma-separated IDs for individual",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["audience"], name="communicati_audienc_498ce3_idx"
            ),
        ),
    ]
