# Generated by Django 5.2.9 on 2026-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0007_announcement_audience_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="provider_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Message ID from SMS provider for delivery tracking",
                max_length=100,
            ),
        ),
    ]
