# Generated by Django 5.2.9 on 2025-12-20 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0004_add_academic_period_type"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_on", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("promoted", "Promoted"),
                            ("repeated", "Repeated"),
                            ("withdrawn", "Withdrawn"),
                            ("transferred", "Transferred"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Notes about this enrollment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="core.academicyear",
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.class",
                    ),
                ),
                (
                    "promoted_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="The enrollment this student was promoted from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_to",
                        to="students.enrollment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "ordering": ["-academic_year__start_date", "student__last_name"],
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
