# Generated by Django 5.2.9 on 2025-12-30 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="occupation"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
                "ordering": ["full_name"],
            },
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_relationship",
        ),
        migrations.AddField(
            model_name="student",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.guardian",
            ),
        ),
    ]
