# Generated by Django 5.2.9 on 2025-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_guardian_remove_student_guardian_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian_relationship",
            field=models.CharField(
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("guardian", "Guardian"),
                    ("uncle", "Uncle"),
                    ("aunt", "Aunt"),
                    ("grandparent", "Grandparent"),
                    ("sibling", "Sibling"),
                    ("other", "Other"),
                ],
                default="guardian",
                max_length=20,
            ),
        ),
    ]
