# Generated by Django 5.2.9 on 2025-12-31 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_add_student_subject_enrollment"),
        ("core", "0003_alter_schoolsettings_sms_backend"),
        ("students", "0003_student_guardian_relationship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["academic_year"], name="students_en_academi_81edac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="students_en_status_c844f7_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["academic_year", "status"],
                name="students_en_academi_53f5bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["class_assigned"], name="students_en_class_a_a2f338_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_st_status_5e2210_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_class"], name="students_st_current_ad0594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_class", "status"],
                name="students_st_current_96d1af_idx",
            ),
        ),
    ]
