# Generated by Django 5.2.9 on 2025-12-31 12:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_guardian_data(apps, schema_editor):
    """Migrate existing guardian relationships to StudentGuardian model."""
    Student = apps.get_model('students', 'Student')
    StudentGuardian = apps.get_model('students', 'StudentGuardian')

    for student in Student.objects.filter(guardian__isnull=False):
        StudentGuardian.objects.create(
            student=student,
            guardian=student.guardian,
            relationship=student.guardian_relationship or 'guardian',
            is_primary=True,  # Existing guardian becomes primary
            is_emergency_contact=True,
        )


def reverse_guardian_data(apps, schema_editor):
    """Reverse migration - copy primary guardian back to student."""
    Student = apps.get_model('students', 'Student')
    StudentGuardian = apps.get_model('students', 'StudentGuardian')

    for sg in StudentGuardian.objects.filter(is_primary=True):
        sg.student.guardian = sg.guardian
        sg.student.guardian_relationship = sg.relationship
        sg.student.save()


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_indexes"),
    ]

    operations = [
        # Step 1: Create the StudentGuardian through model
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        default="guardian",
                        max_length=20,
                        verbose_name="relationship",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary guardian/contact?",
                        verbose_name="primary guardian",
                    ),
                ),
                (
                    "is_emergency_contact",
                    models.BooleanField(
                        default=True,
                        help_text="Can be contacted in emergencies?",
                        verbose_name="emergency contact",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_students",
                        to="students.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_guardians",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Guardian",
                "verbose_name_plural": "Student Guardians",
                "ordering": ["-is_primary", "guardian__full_name"],
                "unique_together": {("student", "guardian")},
            },
        ),
        # Step 2: Add the M2M field
        migrations.AddField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                blank=True,
                related_name="wards",
                through="students.StudentGuardian",
                to="students.guardian",
            ),
        ),
        # Step 3: Migrate existing data
        migrations.RunPython(migrate_guardian_data, reverse_guardian_data),
        # Step 4: Remove old fields
        migrations.RemoveField(
            model_name="student",
            name="guardian",
        ),
        migrations.RemoveField(
            model_name="student",
            name="guardian_relationship",
        ),
    ]
