# Generated by Django 5.2.9 on 2026-01-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_add_studentguardian_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Blue House, Nkrumah House",
                        max_length=50,
                        unique=True,
                        verbose_name="house name",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Blue, Red, Green",
                        max_length=30,
                        verbose_name="color name",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code e.g., #3B82F6",
                        max_length=7,
                        verbose_name="color code",
                    ),
                ),
                (
                    "motto",
                    models.CharField(blank=True, max_length=255, verbose_name="motto"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="house",
            field=models.ForeignKey(
                blank=True,
                help_text="School house the student belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.house",
            ),
        ),
    ]
