# Generated by Django 5.2.9 on 2026-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_house_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['phone_number'], name='students_gdn_phone_idx'),
        ),
    ]
