# Generated by Django 5.2.9 on 2026-01-15 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_students_st_is_acti_c00e81_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account for guardian portal login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuardianInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Secure token for invitation link', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email address invitation was sent to', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_guardian_invitations', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='students.guardian')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='guardian_inv_token_idx'), models.Index(fields=['status'], name='guardian_inv_status_idx')],
            },
        ),
    ]
