# Generated by Django 5.2.9 on 2026-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_add_guardian_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="academic_alerts",
            field=models.BooleanField(default=True, verbose_name="academic alerts"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="announcement_alerts",
            field=models.BooleanField(default=True, verbose_name="announcement alerts"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="attendance_alerts",
            field=models.BooleanField(default=True, verbose_name="attendance alerts"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="email_notifications",
            field=models.BooleanField(default=True, verbose_name="email notifications"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="fee_alerts",
            field=models.BooleanField(default=True, verbose_name="fee alerts"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="sms_notifications",
            field=models.BooleanField(default=True, verbose_name="SMS notifications"),
        ),
    ]
