# Generated by Django 5.2.9 on 2026-01-21 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_is_current_indexes"),
        ("students", "0011_add_missing_indexes"),
        ("teachers", "0004_add_missing_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exeat_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal (Within town, same day return)"),
                            ("external", "External (Outside school location)"),
                        ],
                        default="internal",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the exeat request")),
                (
                    "destination",
                    models.CharField(
                        help_text="Where the student is going", max_length=255
                    ),
                ),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("expected_return_date", models.DateField()),
                ("expected_return_time", models.TimeField()),
                ("actual_return", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("recommended", "Recommended"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active (Student out)"),
                            ("completed", "Completed (Returned)"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("recommended_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("guardian_notified_approval", models.BooleanField(default=False)),
                ("guardian_notified_return", models.BooleanField(default=False)),
                ("guardian_notified_overdue", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exeats_approved",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "housemaster",
                    models.ForeignKey(
                        help_text="The student's housemaster handling this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exeats_as_housemaster",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Housemaster who recommended (external exeats)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exeats_recommended",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exeat_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exeats",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exeat",
                "verbose_name_plural": "Exeats",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="students_ex_status_00badb_idx"
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="students_ex_student_c183cd_idx",
                    ),
                    models.Index(
                        fields=["exeat_type", "status"],
                        name="students_ex_exeat_t_3569f2_idx",
                    ),
                    models.Index(
                        fields=["departure_date"], name="students_ex_departu_b1a8d7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HouseMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_senior",
                    models.BooleanField(
                        default=False,
                        help_text="Senior Housemaster (Discipline Master) - approves external exeats",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housemaster_assignments",
                        to="core.academicyear",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housemaster_assignments",
                        to="students.house",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housemaster_assignments",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "House Master",
                "verbose_name_plural": "House Masters",
                "ordering": ["-academic_year__start_date", "house__name"],
                "unique_together": {("house", "academic_year")},
            },
        ),
    ]
