# Generated by Django 5.2.9 on 2026-01-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_add_housemaster_and_exeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="exeat",
            name="actual_departure",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exeat",
            name="contact_person",
            field=models.CharField(
                blank=True, help_text="Emergency contact person name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="exeat",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Emergency contact phone", max_length=20
            ),
        ),
    ]
