# Generated by Django 5.2.9 on 2026-01-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_add_exeat_sms_tracking"),
        ("students", "0013_add_exeat_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="exeat",
            name="approval_sms",
            field=models.ForeignKey(
                blank=True,
                help_text="SMS sent when exeat was approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exeat_approvals",
                to="communications.smsmessage",
            ),
        ),
        migrations.AddField(
            model_name="exeat",
            name="return_sms",
            field=models.ForeignKey(
                blank=True,
                help_text="SMS sent when student returned",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exeat_returns",
                to="communications.smsmessage",
            ),
        ),
    ]
