# Generated by Django 5.2.9 on 2026-02-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_student_residence_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_is_acti_c00e81_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_is_acti_8a4dcc_idx",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="academic_alerts",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="announcement_alerts",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="attendance_alerts",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="fee_alerts",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="sms_notifications",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_active",
        ),
    ]
