# Generated by Django 5.2.9 on 2026-02-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_branding_from_schoolsettings"),
        ("students", "0017_simplify_student_models"),
        ("teachers", "0009_remove_teacherdocument_teacher_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="housemaster",
            unique_together={("house", "academic_year", "teacher")},
        ),
    ]
