# Generated by Django 5.2.9 on 2026-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_allow_multiple_housemasters_per_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="class_name",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of class name at time of enrollment",
                max_length=20,
            ),
        ),
    ]
