# Generated by Django 5.2.9 on 2026-02-11 13:39

from django.db import migrations


def backfill_class_name(apps, schema_editor):
    Enrollment = apps.get_model('students', 'Enrollment')
    batch = []
    for enrollment in Enrollment.objects.filter(class_name='').select_related('class_assigned').iterator(chunk_size=500):
        enrollment.class_name = enrollment.class_assigned.name
        batch.append(enrollment)
        if len(batch) >= 500:
            Enrollment.objects.bulk_update(batch, ['class_name'])
            batch = []
    if batch:
        Enrollment.objects.bulk_update(batch, ['class_name'])


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_add_class_name_to_enrollment"),
    ]

    operations = [
        migrations.RunPython(backfill_class_name, migrations.RunPython.noop),
    ]
