# Generated by Django 5.2.9 on 2026-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_backfill_enrollment_class_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="guardianinvitation",
            name="guardian_inv_token_idx",
        ),
    ]
