# Generated by Django 5.2.9 on 2026-02-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0021_remove_guardianinvitation_guardian_inv_token_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardianinvitation",
            name="token",
            field=models.CharField(
                help_text="Secure token for invitation link", max_length=64, unique=True
            ),
        ),
    ]
