# Generated by Django 5.2.9 on 2026-02-24 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0022_remove_redundant_db_index_on_token"),
        ("teachers", "0010_remove_redundant_db_index_on_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="exeat",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exeat",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exeats_rejected",
                to="teachers.teacher",
            ),
        ),
    ]
