# Generated by Django 5.2.9 on 2026-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0022_alter_class_unique_together_and_more"),
        ("core", "0015_add_invoice_receipt_document_types"),
        ("students", "0023_add_rejection_audit_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student"], name="students_en_student_167e75_idx"
            ),
        ),
    ]
