# Generated by Django 5.2.9 on 2026-03-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_add_enrollment_student_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="notification_preference",
            field=models.CharField(
                choices=[
                    ("sms", "SMS Only"),
                    ("email", "Email Only"),
                    ("both", "SMS & Email"),
                    ("none", "No Notifications"),
                ],
                default="sms",
                help_text="How this guardian prefers to receive notifications",
                max_length=5,
            ),
        ),
    ]
