# Generated by Django 5.2.9 on 2026-09-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0025_add_guardian_notification_pref"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="religion",
            field=models.CharField(blank=True, max_length=50, verbose_name="religion"),
        ),
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ghana_card_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Ghana Card number"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="health_conditions",
            field=models.TextField(
                blank=True, help_text="Allergies, medical conditions, medications, etc."
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_tongue",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="nhis_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="NHIS card number"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="other_languages",
            field=models.CharField(
                blank=True,
                help_text="Other languages spoken (comma-separated)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="siblings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other enrolled students who are this student's siblings",
                to="students.student",
            ),
        ),
    ]
