# Generated by Django 5.2.9 on 2025-12-28 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 2024/2025 Academic Year", max_length=50
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Only one academic year can be current at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="school_favicons/"
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=50)),
                ("motto", models.CharField(blank=True, max_length=200)),
                (
                    "academic_period_type",
                    models.CharField(
                        choices=[
                            ("term", "Terms (Primary/JHS)"),
                            ("semester", "Semesters (SHS)"),
                        ],
                        default="term",
                        help_text="Terms for Primary/JHS, Semesters for SHS",
                        max_length=10,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5", help_text="Main brand color", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#7C3AED",
                        help_text="Secondary brand color",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#F59E0B",
                        help_text="Accent/highlight color",
                        max_length=7,
                    ),
                ),
                (
                    "primary_color_oklch",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                (
                    "secondary_color_oklch",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                (
                    "accent_color_oklch",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
            ],
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., First Term, Semester One", max_length=50
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Third"),
                            (4, "Fourth"),
                        ],
                        default=1,
                        verbose_name="Period Number",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Only one term can be current at a time",
                    ),
                ),
                (
                    "grades_locked",
                    models.BooleanField(
                        default=False,
                        help_text="When locked, scores cannot be modified",
                    ),
                ),
                (
                    "grades_locked_at",
                    models.DateTimeField(
                        blank=True, help_text="When grades were locked", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="core.academicyear",
                    ),
                ),
                (
                    "grades_locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who locked the grades",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_terms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "ordering": ["academic_year", "term_number"],
                "unique_together": {("academic_year", "term_number")},
            },
        ),
    ]
