# Generated by Django 5.2.9 on 2025-12-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                ("display_name", models.CharField(blank=True, max_length=50)),
                ("motto", models.CharField(blank=True, max_length=200)),
                ("primary_color", models.CharField(default="#4F46E5", max_length=7)),
                (
                    "primary_color_oklch",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
            ],
        ),
    ]
