# Generated by Django 5.2.9 on 2025-12-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolsettings",
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
            },
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="accent_color",
            field=models.CharField(
                default="#F59E0B", help_text="Accent/highlight color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="accent_color_oklch",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="favicon",
            field=models.ImageField(
                blank=True, null=True, upload_to="school_favicons/"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="secondary_color",
            field=models.CharField(
                default="#7C3AED", help_text="Secondary brand color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="secondary_color_oklch",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="primary_color",
            field=models.CharField(
                default="#4F46E5", help_text="Main brand color", max_length=7
            ),
        ),
    ]
