# Generated by Django 5.2.9 on 2025-12-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="sms_api_key",
            field=models.CharField(
                blank=True,
                help_text="Arkesel API key (get from https://sms.arkesel.com/user/sms-api/info)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="sms_backend",
            field=models.CharField(
                choices=[("console", "Console (Development)"), ("arkesel", "Arkesel")],
                default="console",
                help_text="SMS provider to use for sending messages",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="sms_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable SMS messaging for this school"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="sms_sender_id",
            field=models.CharField(
                blank=True,
                help_text="Sender ID shown on SMS (max 11 characters)",
                max_length=11,
            ),
        ),
    ]
