# Generated by Django 5.2.9 on 2025-12-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_sms_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="sms_backend",
            field=models.CharField(
                choices=[
                    ("console", "Console (Development)"),
                    ("arkesel", "Arkesel"),
                    ("hubtel", "Hubtel"),
                    ("africastalking", "Africa's Talking"),
                ],
                default="console",
                help_text="SMS provider to use for sending messages",
                max_length=20,
            ),
        ),
    ]
