# Generated by Django 5.2.9 on 2025-12-31 15:56

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_schoolsettings_sms_backend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        db_index=True,
                        default=core.models.generate_verification_code,
                        help_text="Unique code for document verification",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("report_card", "Report Card"),
                            ("transcript", "Transcript"),
                            ("student_profile", "Student Profile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("student_admission_number", models.CharField(max_length=50)),
                (
                    "document_title",
                    models.CharField(
                        help_text="e.g., 'Report Card - Term 1 2024/2025'",
                        max_length=200,
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=50)),
                ("term_id", models.CharField(blank=True, max_length=50)),
                ("academic_year", models.CharField(blank=True, max_length=100)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("verification_count", models.PositiveIntegerField(default=0)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Verification",
                "verbose_name_plural": "Document Verifications",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["verification_code"],
                        name="core_docume_verific_17bc16_idx",
                    ),
                    models.Index(
                        fields=["student_admission_number"],
                        name="core_docume_student_5cac92_idx",
                    ),
                    models.Index(
                        fields=["document_type", "generated_at"],
                        name="core_docume_documen_8f8e7f_idx",
                    ),
                ],
            },
        ),
    ]
