# Generated by Django 5.2.9 on 2025-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_academicyear_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="academic_period_type",
            field=models.CharField(
                choices=[
                    ("term", "Terms (Primary/JHS)"),
                    ("semester", "Semesters (SHS)"),
                ],
                default="term",
                help_text="Terms for Primary/JHS, Semesters for SHS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="name",
            field=models.CharField(
                help_text="e.g., First Term, Semester One", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="term_number",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "First"), (2, "Second"), (3, "Third"), (4, "Fourth")],
                default=1,
                verbose_name="Period Number",
            ),
        ),
    ]
