# Generated by Django 5.2.9 on 2026-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_document_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("report_card", "Report Card"),
                    ("transcript", "Transcript"),
                    ("student_profile", "Student Profile"),
                    ("staff_profile", "Staff Profile"),
                ],
                max_length=20,
            ),
        ),
    ]
