# Generated by Django 5.2.9 on 2025-12-27 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_academic_period_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="grades_locked",
            field=models.BooleanField(
                default=False, help_text="When locked, scores cannot be modified"
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="grades_locked_at",
            field=models.DateTimeField(
                blank=True, help_text="When grades were locked", null=True
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="grades_locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who locked the grades",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
