# Generated by Django 5.2.9 on 2026-01-05 00:58

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_documentverification_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="email_backend",
            field=models.CharField(
                choices=[("console", "Console (Development)"), ("smtp", "SMTP")],
                default="console",
                help_text="Email provider to use",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable custom email settings for this school"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_from_address",
            field=models.EmailField(
                blank=True, help_text="Default 'From' email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_from_name",
            field=models.CharField(
                blank=True, help_text="Display name for 'From' address", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="SMTP server hostname (e.g., smtp.gmail.com)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_host_password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="SMTP password (encrypted)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="SMTP username/email", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_port",
            field=models.PositiveIntegerField(
                default=587, help_text="SMTP port (587 for TLS, 465 for SSL)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_use_ssl",
            field=models.BooleanField(
                default=False,
                help_text="Use SSL encryption (mutually exclusive with TLS)",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="email_use_tls",
            field=models.BooleanField(default=True, help_text="Use TLS encryption"),
        ),
    ]
