# Generated by Django 5.2.9 on 2026-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Whether the initial setup wizard has been completed'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, help_text='When setup was completed', null=True),
        ),
    ]
