# Generated by Django 5.2.9 on 2026-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='academic_period_type',
            field=models.CharField(choices=[('term', 'Terms (Basic)'), ('semester', 'Semesters (SHS)')], default='term', help_text='Terms for Basic, Semesters for SHS', max_length=10),
        ),
    ]
