# Generated by Django 5.2.9 on 2026-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_update_period_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="education_system",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Only (Creche - Basic 9)"),
                    ("shs", "SHS Only"),
                    ("both", "Both Basic and SHS"),
                ],
                default="both",
                help_text="Which educational levels this school supports",
                max_length=10,
            ),
        ),
    ]
