# Generated by Django 5.2 on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_education_system_to_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Only one academic year can be current at a time'
            ),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Only one term can be current at a time'
            ),
        ),
    ]
