# Generated by Django 5.2.9 on 2026-01-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_is_current_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolsettings",
            name="accent_color",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="accent_color_oklch",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="education_system",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="motto",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="primary_color_oklch",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="schoolsettings",
            name="secondary_color_oklch",
        ),
    ]
