# Generated by Django 5.2.9 on 2026-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_branding_from_schoolsettings"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentverification",
            name="core_docume_verific_17bc16_idx",
        ),
    ]
