# Generated by Django 5.2.9 on 2026-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_documentverification_core_docume_verific_17bc16_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="sms_webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secret token for SMS delivery webhook verification",
                max_length=64,
            ),
        ),
    ]
