# Generated by Django 5.2.9 on 2026-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sms_delivery_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentverification",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("report_card", "Report Card"),
                    ("transcript", "Transcript"),
                    ("student_profile", "Student Profile"),
                    ("staff_profile", "Staff Profile"),
                    ("invoice", "Invoice"),
                    ("receipt", "Receipt"),
                ],
                max_length=20,
            ),
        ),
    ]
