# Generated by Django 5.2.9 on 2026-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_invoice_receipt_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_aggregate",
            field=models.BooleanField(
                default=True, help_text="Show aggregate score (SHS)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_attendance",
            field=models.BooleanField(
                default=True, help_text="Show attendance record section"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_class_teacher",
            field=models.BooleanField(
                default=True, help_text="Show class teacher name on report card"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_conduct",
            field=models.BooleanField(
                default=True, help_text="Show conduct & behavior section"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_grading_key",
            field=models.BooleanField(
                default=True, help_text="Show grading scale key in footer"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_position",
            field=models.BooleanField(
                default=True, help_text="Show student position/ranking"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_promotion",
            field=models.BooleanField(default=True, help_text="Show promotion status"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_qr_code",
            field=models.BooleanField(
                default=True, help_text="Show QR verification code"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_show_student_photo",
            field=models.BooleanField(
                default=True, help_text="Show student photo on report card"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_title",
            field=models.CharField(
                default="Terminal Report Card",
                help_text="Custom report card title",
                max_length=100,
            ),
        ),
    ]
