# Generated by Django 5.2.9 on 2026-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_report_card_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="rc_display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom school name for report card. Use | to split into two lines.",
                max_length=200,
            ),
        ),
    ]
