# Generated by Django 5.2.9 on 2026-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_rc_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="absence_sms_template",
            field=models.TextField(
                blank=True,
                default="Dear Parent, {student_name} has been absent from {school_name} for {days} consecutive day(s) ({dates}). Please contact the school if your child is unwell. Thank you.",
                help_text="SMS template for absence alerts. Placeholders: {student_name}, {school_name}, {days}, {dates}",
            ),
        ),
    ]
