# Generated by Django 5.2.9 on 2026-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_absence_sms_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="grade_alert_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Send SMS to parents when student average drops below threshold",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="grade_alert_sms_template",
            field=models.TextField(
                blank=True,
                default="Dear Parent, {student_name}'s current average in {class_name} is {average}% ({term}). Please encourage them to improve. - {school_name}",
                help_text="SMS for grade alerts. Placeholders: {student_name}, {class_name}, {average}, {term}, {school_name}, {position}",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="grade_alert_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Average percentage below which parents are notified",
                max_digits=5,
            ),
        ),
    ]
