# Generated by Django 5.2.9 on 2026-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_grade_alert_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="auto_distribute_on_lock",
            field=models.BooleanField(
                default=False,
                help_text="Automatically distribute reports via email when grades are locked",
            ),
        ),
    ]
