# Generated by Django 5.2.9 on 2026-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_auto_distribute_on_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="scheduled_report_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule automatic report distribution at this date/time",
                null=True,
            ),
        ),
    ]
