# Generated by Django 5.2.9 on 2026-03-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_scheduled_report_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Republic Day, Farmers' Day", max_length=100
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "recurring_annually",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this holiday applies every year on the same month/day.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "School Holiday",
                "verbose_name_plural": "School Holidays",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date",), name="unique_holiday_date"
                    )
                ],
            },
        ),
    ]
