# Generated by Django 5.2.9 on 2026-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_school_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="school_days",
            field=models.CharField(
                default="1,2,3,4,5",
                help_text="Working days as comma-separated weekday numbers (1=Monday, 5=Friday, 6=Saturday)",
                max_length=20,
            ),
        ),
    ]
