# Generated by Django 5.2.9 on 2026-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_school_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="allow_past_term_attendance",
            field=models.BooleanField(
                default=False,
                help_text="Allow teachers and admins to mark or edit attendance for dates before the current term started (e.g. a past semester), as long as the date falls within a previously defined term.",
            ),
        ),
    ]
