# Generated by Django 5.2.9 on 2026-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_allow_past_term_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="school_days",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override the school's default working days for this term only. Leave blank to use the school default.",
                max_length=20,
            ),
        ),
    ]
