# Generated by Django 5.2.9 on 2026-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_term_school_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="head_teacher_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional note shown on every report card for this term (e.g. reopening date, a closing remark).",
            ),
        ),
    ]
