# Generated by Django 5.2.9 on 2025-12-30 19:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_add_student_subject_enrollment"),
        ("core", "0003_alter_schoolsettings_sms_backend"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition/School Fees"),
                            ("ADMISSION", "Admission Fees"),
                            ("EXAM", "Examination Fees"),
                            ("PTA", "PTA Dues"),
                            ("SPORTS", "Sports & Extra-curricular"),
                            ("ICT", "ICT/Computer Lab"),
                            ("LIBRARY", "Library Fees"),
                            ("BOARDING", "Boarding Fees"),
                            ("FEEDING", "Feeding Fees"),
                            ("TRANSPORT", "Transport/Bus Fees"),
                            ("UNIFORM", "Uniform & Materials"),
                            ("CAUTION", "Caution Deposit"),
                            ("OTHER", "Other Fees"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_recurring",
                    models.BooleanField(default=True, help_text="Charged every term"),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applies_to_boarding",
                    models.BooleanField(
                        default=True, help_text="Applies to boarding students"
                    ),
                ),
                (
                    "applies_to_day",
                    models.BooleanField(
                        default=True, help_text="Applies to day students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("FLUTTERWAVE", "Flutterwave"),
                            ("HUBTEL", "Hubtel"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("supports_mobile_money", models.BooleanField(default=True)),
                ("supports_cards", models.BooleanField(default=True)),
                ("supports_bank_transfer", models.BooleanField(default=False)),
                (
                    "setup_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for schools to set up this gateway",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All Levels"),
                            ("KG", "Kindergarten"),
                            ("PRIMARY", "Primary (B1-B6)"),
                            ("JHS", "JHS (B7-B9)"),
                            ("SHS", "SHS"),
                        ],
                        help_text="Apply to all classes of this level",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="core.academicyear",
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply by level type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="academics.class",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        help_text="SHS programme (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="academics.programme",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for full year fee",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="core.term",
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="finance.feetype",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year", "term", "fee_type"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.feetype",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CARD", "Card Payment"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payer_name", models.CharField(blank=True, max_length=200)),
                ("payer_phone", models.CharField(blank=True, max_length=20)),
                ("payer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank/Mobile money reference",
                        max_length=200,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.invoice",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Gateway secret/private key"
                    ),
                ),
                (
                    "public_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, help_text="Gateway public key"
                    ),
                ),
                (
                    "webhook_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, help_text="Webhook verification secret"
                    ),
                ),
                (
                    "merchant_id",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, help_text="Merchant/Client ID"
                    ),
                ),
                (
                    "encryption_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, help_text="Encryption key (for Flutterwave)"
                    ),
                ),
                (
                    "merchant_account",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, help_text="Merchant account (for Hubtel)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_test_mode",
                    models.BooleanField(
                        default=True, help_text="Enable test/sandbox mode"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary gateway for this school"
                    ),
                ),
                (
                    "transaction_charge_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional charge percentage to add to transactions",
                        max_digits=5,
                    ),
                ),
                (
                    "transaction_charge_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed amount to add to transactions",
                        max_digits=10,
                    ),
                ),
                (
                    "who_bears_charge",
                    models.CharField(
                        choices=[
                            ("SCHOOL", "School bears charges"),
                            ("PARENT", "Parent bears charges"),
                        ],
                        default="SCHOOL",
                        max_length=20,
                    ),
                ),
                ("configured_at", models.DateTimeField(auto_now_add=True)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("FAILED", "Verification Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verification_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_gateways",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_configs",
                        to="finance.paymentgateway",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "gateway__display_name"],
                "unique_together": {("gateway",)},
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_reference", models.CharField(blank=True, max_length=200)),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("authorization_code", models.CharField(blank=True, max_length=200)),
                (
                    "amount_charged",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "gateway_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("full_response", models.JSONField(blank=True, null=True)),
                ("callback_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.paymentgatewayconfig",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_transaction",
                        to="finance.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                            ("FULL", "Full Scholarship"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount in GHS",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_fee_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave blank to apply to all fees",
                        to="finance.feetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for awarding scholarship"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_scholarships",
                        to="core.academicyear",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scholarships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="finance.scholarship",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("student", "scholarship", "academic_year")},
            },
        ),
    ]
