# Generated by Django 5.2.9 on 2026-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feestructure",
            name="fee_type",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="applies_to_fee_types",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="fee_type",
        ),
        migrations.AlterModelOptions(
            name="feestructure",
            options={"ordering": ["academic_year", "term", "category"]},
        ),
        migrations.AddField(
            model_name="feestructure",
            name="applies_to_boarding",
            field=models.BooleanField(
                default=True, help_text="Applies to boarding students"
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="applies_to_day",
            field=models.BooleanField(
                default=True, help_text="Applies to day students"
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="category",
            field=models.CharField(
                choices=[
                    ("TUITION", "Tuition/School Fees"),
                    ("ADMISSION", "Admission Fees"),
                    ("EXAM", "Examination Fees"),
                    ("PTA", "PTA Dues"),
                    ("SPORTS", "Sports & Extra-curricular"),
                    ("ICT", "ICT/Computer Lab"),
                    ("LIBRARY", "Library Fees"),
                    ("BOARDING", "Boarding Fees"),
                    ("FEEDING", "Feeding Fees"),
                    ("TRANSPORT", "Transport/Bus Fees"),
                    ("UNIFORM", "Uniform & Materials"),
                    ("CAUTION", "Caution Deposit"),
                    ("OTHER", "Other Fees"),
                ],
                default="TUITION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="is_mandatory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("TUITION", "Tuition/School Fees"),
                    ("ADMISSION", "Admission Fees"),
                    ("EXAM", "Examination Fees"),
                    ("PTA", "PTA Dues"),
                    ("SPORTS", "Sports & Extra-curricular"),
                    ("ICT", "ICT/Computer Lab"),
                    ("LIBRARY", "Library Fees"),
                    ("BOARDING", "Boarding Fees"),
                    ("FEEDING", "Feeding Fees"),
                    ("TRANSPORT", "Transport/Bus Fees"),
                    ("UNIFORM", "Uniform & Materials"),
                    ("CAUTION", "Caution Deposit"),
                    ("OTHER", "Other Fees"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="applies_to_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of category codes. Empty = applies to all fees",
            ),
        ),
        migrations.DeleteModel(
            name="FeeType",
        ),
    ]
