# Generated by Django 5.2.9 on 2026-01-02 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_add_indexes"),
        ("finance", "0002_simplify_remove_feetype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceNotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_ISSUED", "Invoice Issued"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("OVERDUE_REMINDER", "Overdue Reminder"),
                            ("BALANCE_REMINDER", "Balance Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email with PDF"),
                            ("SMS", "SMS Summary"),
                            ("BOTH", "Email and SMS"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("email_sent_to", models.EmailField(blank=True, max_length=254)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_error", models.TextField(blank=True)),
                (
                    "sms_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sms_sent_to", models.CharField(blank=True, max_length=20)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sms_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="finance.invoice",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sms_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_notifications",
                        to="communications.smsmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Notification Log",
                "verbose_name_plural": "Finance Notification Logs",
                "db_table": "finance_notification_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "-created_at"],
                        name="finance_not_invoice_1b19d6_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="finance_not_notific_314e27_idx",
                    ),
                    models.Index(
                        fields=["email_status"], name="finance_not_email_s_48d0cf_idx"
                    ),
                    models.Index(
                        fields=["sms_status"], name="finance_not_sms_sta_834120_idx"
                    ),
                ],
            },
        ),
    ]
