# Generated by Django 5.2.9 on 2026-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoice_finance_inv_student_7ec268_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='level_type',
            field=models.CharField(blank=True, choices=[('', 'All Levels'), ('creche', 'Creche'), ('nursery', 'Nursery'), ('kg', 'Kindergarten'), ('basic', 'Basic (B1-B9)'), ('shs', 'SHS')], help_text='Apply to all classes of this level', max_length=10),
        ),
    ]
