# Generated by Django 5.2.9 on 2026-03-02 08:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_update_level_type_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("GCB", "GCB Bank"),
                            ("ECOBANK", "Ecobank"),
                            ("STANBIC", "Stanbic Bank"),
                            ("FIDELITY", "Fidelity Bank"),
                            ("GENERIC", "Other / Generic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("credit_rows", models.PositiveIntegerField(default=0)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("confirmed_count", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "confirmed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("reference", models.CharField(blank=True, max_length=500)),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Unmatched"),
                            ("SKIPPED", "Skipped"),
                            ("DUPLICATE", "Duplicate"),
                            ("CONFIRMED", "Confirmed"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="UNMATCHED",
                        max_length=20,
                    ),
                ),
                ("match_method", models.CharField(blank=True, max_length=50)),
                (
                    "match_confidence",
                    models.CharField(
                        blank=True, help_text="high / medium / low", max_length=10
                    ),
                ),
                (
                    "matched_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_rows",
                        to="finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_rows",
                        to="finance.payment",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="finance.bankreconciliation",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
                "indexes": [
                    models.Index(
                        fields=["reconciliation", "match_status"],
                        name="finance_ban_reconci_20c7f9_idx",
                    )
                ],
            },
        ),
    ]
