# Generated by Django 5.2.9 on 2025-12-21 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("phone_number", models.CharField(blank=True, max_length=17)),
                ("address", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("nationality", models.CharField(default="Ghanaian", max_length=50)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr."),
                            ("Mrs", "Mrs."),
                            ("Miss", "Miss"),
                            ("Dr", "Dr."),
                            ("Prof", "Prof."),
                        ],
                        default="Mr",
                        max_length=10,
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        help_text="Unique Employee ID", max_length=20, unique=True
                    ),
                ),
                (
                    "subject_specialization",
                    models.CharField(
                        help_text="e.g. Mathematics, Science", max_length=100
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
