# Generated by Django 5.2.9 on 2025-12-28 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("phone_number", models.CharField(blank=True, max_length=17)),
                ("address", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("nationality", models.CharField(default="Ghanaian", max_length=50)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("MR", "Mr."),
                            ("MRS", "Mrs."),
                            ("MS", "Ms."),
                            ("DR", "Dr."),
                            ("REV", "Rev."),
                            ("PROF", "Prof."),
                            ("PST", "Pastor"),
                        ],
                        default="MR",
                        max_length=10,
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        help_text="Unique Employee ID", max_length=20, unique=True
                    ),
                ),
                (
                    "subject_specialization",
                    models.CharField(
                        help_text="e.g. Mathematics, Science", max_length=100
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated user account for login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
