# Generated by Django 5.2.9 on 2026-02-07 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_add_missing_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalDevelopment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the activity/course", max_length=255
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("course", "Course"),
                            ("conference", "Conference"),
                            ("certification", "Certification"),
                            ("training", "Training"),
                            ("webinar", "Webinar"),
                            ("seminar", "Seminar"),
                            ("other", "Other"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Institution or organization providing the training",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="CPD hours/credits earned",
                        max_digits=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                (
                    "certificate_expiry",
                    models.DateField(
                        blank=True,
                        help_text="When this certification expires (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload certificate document",
                        upload_to="pd_certificates/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or learnings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pd_activities",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Development",
                "verbose_name_plural": "Professional Development Activities",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "status"], name="pd_teacher_status_idx"
                    ),
                    models.Index(fields=["start_date"], name="pd_start_date_idx"),
                    models.Index(
                        fields=["certificate_expiry"], name="pd_cert_expiry_idx"
                    ),
                ],
            },
        ),
    ]
