# Generated by Django 5.2.9 on 2026-02-07 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_add_professional_development"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Employment Contract"),
                            ("qualification", "Qualification/Degree"),
                            ("certification", "Professional Certification"),
                            ("id_document", "ID Document"),
                            ("reference", "Reference Letter"),
                            ("medical", "Medical Certificate"),
                            ("background_check", "Background Check"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Accepted formats: PDF, JPG, PNG, DOC, DOCX",
                        upload_to="teacher_documents/",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if document doesn't expire",
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this document been verified by admin?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_teacher_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Document",
                "verbose_name_plural": "Teacher Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "document_type"], name="doc_teacher_type_idx"
                    ),
                    models.Index(fields=["expiry_date"], name="doc_expiry_idx"),
                ],
            },
        ),
    ]
