# Generated by Django 5.2.9 on 2026-02-09 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_add_teacher_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="date_posted_to_current_school",
            field=models.DateField(
                blank=True,
                help_text="Date posted/transferred to current school",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="ghana_card_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ghana Card (GHA-XXXXXXXXX-X)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="licence_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Teaching licence/registration number",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="ssnit_number",
            field=models.CharField(
                blank=True, default="", help_text="SSNIT number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="staff_category",
            field=models.CharField(
                choices=[("teaching", "Teaching"), ("non_teaching", "Non-Teaching")],
                default="teaching",
                help_text="Teaching or non-teaching staff",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        help_text="e.g. Principal Superintendent, Assistant Director",
                        max_length=100,
                    ),
                ),
                ("date_promoted", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_promoted"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "date_promoted"],
                        name="promo_teacher_date_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. B.Ed, M.Phil, Diploma in Education",
                        max_length=255,
                    ),
                ),
                (
                    "institution",
                    models.CharField(help_text="Awarding institution", max_length=255),
                ),
                ("date_started", models.DateField(blank=True, null=True)),
                ("date_ended", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="completed",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_ended", "-date_started"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "status"], name="qual_teacher_status_idx"
                    )
                ],
            },
        ),
    ]
