# Generated by Django 5.2.9 on 2026-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_teacher_date_posted_to_current_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="date_posted_to_current_school",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="ghana_card_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="licence_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="ssnit_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="staff_category",
            field=models.CharField(
                choices=[("teaching", "Teaching"), ("non_teaching", "Non-Teaching")],
                default="teaching",
                max_length=15,
            ),
        ),
    ]
