# Generated by Django 5.2.9 on 2026-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_alter_teacher_date_posted_to_current_school_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherdocument",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="teacherdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject_specialization",
        ),
        migrations.AlterField(
            model_name="promotion",
            name="rank",
            field=models.CharField(
                choices=[
                    ("supt_ii", "Superintendent II"),
                    ("supt_i", "Superintendent I"),
                    ("snr_supt_ii", "Senior Superintendent II"),
                    ("snr_supt_i", "Senior Superintendent I"),
                    ("prin_supt", "Principal Superintendent"),
                    ("asst_dir_ii", "Assistant Director II"),
                    ("asst_dir_i", "Assistant Director I"),
                    ("dep_dir", "Deputy Director"),
                    ("director", "Director"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ProfessionalDevelopment",
        ),
        migrations.DeleteModel(
            name="TeacherDocument",
        ),
    ]
