# Generated by Django 5.2.9 on 2026-02-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0009_remove_teacherdocument_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherinvitation",
            name="token",
            field=models.CharField(
                help_text="Secure token for invitation link", max_length=64, unique=True
            ),
        ),
    ]
