# Generated by Django 5.2.9 on 2025-12-26 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0005_remove_subject_level_fields"),
        ("core", "0004_add_academic_period_type"),
        ("students", "0002_add_enrollment_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the grading system (e.g., WASSCE, BECE, Custom)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic School"),
                            ("SHS", "Senior High School"),
                        ],
                        help_text="School level this grading system is for",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grading System",
                "verbose_name_plural": "Grading Systems",
                "db_table": "grading_system",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Class Score, Examination)",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short code (e.g., CA, EXAM)", max_length=10
                    ),
                ),
                (
                    "percentage",
                    models.IntegerField(
                        help_text="Weight percentage for this category (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assessment Category",
                "verbose_name_plural": "Assessment Categories",
                "db_table": "assessment_category",
                "ordering": ["order", "name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Assignment name (e.g., Quiz 1, Mid-term Test)",
                        max_length=100,
                    ),
                ),
                (
                    "points_possible",
                    models.IntegerField(
                        help_text="Maximum points available for this assignment",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the assignment (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="gradebook.assessmentcategory",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignment",
                "ordering": ["term", "subject", "assessment_category__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_label",
                    models.CharField(
                        help_text="Grade label (e.g., A1, B2, C6 for WASSCE; A, B, C for BECE)",
                        max_length=10,
                    ),
                ),
                (
                    "min_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum percentage for this grade (inclusive)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum percentage for this grade (inclusive)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "aggregate_points",
                    models.IntegerField(
                        blank=True,
                        help_text="Aggregate points for WASSCE/BECE (1-9, where 1 is best)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        help_text="Grade interpretation (e.g., Excellent, Very Good, Credit, Pass, Fail)",
                        max_length=50,
                    ),
                ),
                (
                    "is_pass",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this grade is considered passing",
                    ),
                ),
                (
                    "is_credit",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this grade is a credit pass (relevant for university admission)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scales",
                        to="gradebook.gradingsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Scale",
                "verbose_name_plural": "Grade Scales",
                "db_table": "grade_scale",
                "ordering": ["grading_system", "order", "-min_percentage"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Points earned on this assignment",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="gradebook.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score",
                "verbose_name_plural": "Scores",
                "db_table": "score",
                "ordering": ["student", "assignment"],
            },
        ),
        migrations.CreateModel(
            name="SubjectTermGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class work/CA total percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Examination percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total percentage (class + exam)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="Grade label (e.g., A1, B2)", max_length=5
                    ),
                ),
                (
                    "grade_remark",
                    models.CharField(
                        blank=True,
                        help_text="Grade interpretation (e.g., Excellent)",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Class rank for this subject", null=True
                    ),
                ),
                ("teacher_remark", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_grades",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_grades",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_grades",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Term Grade",
                "verbose_name_plural": "Subject Term Grades",
                "db_table": "subject_term_grade",
                "ordering": ["term", "subject", "-total_score"],
            },
        ),
        migrations.CreateModel(
            name="TermReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all subject scores",
                        max_digits=7,
                    ),
                ),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average percentage across all subjects",
                        max_digits=5,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Overall class position", null=True
                    ),
                ),
                (
                    "out_of",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Total students in class", null=True
                    ),
                ),
                ("subjects_taken", models.PositiveSmallIntegerField(default=0)),
                ("subjects_passed", models.PositiveSmallIntegerField(default=0)),
                ("subjects_failed", models.PositiveSmallIntegerField(default=0)),
                ("class_teacher_remark", models.TextField(blank=True)),
                ("head_teacher_remark", models.TextField(blank=True)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "promoted",
                    models.BooleanField(
                        blank=True,
                        help_text="Promotion status (null = not final term)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_reports",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_reports",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Report",
                "verbose_name_plural": "Term Reports",
                "db_table": "term_report",
                "ordering": ["term", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["subject", "term", "assessment_category"],
                name="assignment_subject_82bdc0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("assessment_category", "subject", "term", "name")},
        ),
        migrations.AddIndex(
            model_name="gradescale",
            index=models.Index(
                fields=["grading_system", "min_percentage", "max_percentage"],
                name="grade_scale_grading_8be02a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradescale",
            unique_together={("grading_system", "grade_label")},
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["student", "assignment"], name="score_student_07461c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("student", "assignment")},
        ),
        migrations.AddIndex(
            model_name="subjecttermgrade",
            index=models.Index(
                fields=["student", "term"], name="subject_ter_student_df6cfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjecttermgrade",
            index=models.Index(
                fields=["subject", "term", "total_score"],
                name="subject_ter_subject_6b00e6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjecttermgrade",
            unique_together={("student", "subject", "term")},
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["term", "average"], name="term_report_term_id_5b99ad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termreport",
            unique_together={("student", "term")},
        ),
    ]
