# Generated by Django 5.2.9 on 2025-12-28 00:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("core", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the grading system (e.g., WASSCE, BECE, Custom)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic School"),
                            ("SHS", "Senior High School"),
                        ],
                        help_text="School level this grading system is for",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Minimum percentage to pass a subject (default 50%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "credit_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Minimum percentage for a credit pass (WASSCE: 50% for C6)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "aggregate_subjects_count",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Number of best subjects used for aggregate calculation (WASSCE: 6)",
                    ),
                ),
                (
                    "min_subjects_to_pass",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minimum subjects a student must pass for promotion (0 = use average only)",
                    ),
                ),
                (
                    "min_average_for_promotion",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Minimum average percentage required for promotion",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "require_core_pass",
                    models.BooleanField(
                        default=True,
                        help_text="Require passing all core subjects for promotion (Ghana standard)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grading System",
                "verbose_name_plural": "Grading Systems",
                "db_table": "grading_system",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Class Score, Examination)",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short code (e.g., CA, EXAM)", max_length=10
                    ),
                ),
                (
                    "percentage",
                    models.IntegerField(
                        help_text="Weight percentage for this category (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assessment Category",
                "verbose_name_plural": "Assessment Categories",
                "db_table": "assessment_category",
                "ordering": ["order", "name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Assignment name (e.g., Quiz 1, Mid-term Test)",
                        max_length=100,
                    ),
                ),
                (
                    "points_possible",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum points available for this assignment",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the assignment (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="gradebook.assessmentcategory",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignment",
                "ordering": ["term", "subject", "assessment_category__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade_label",
                    models.CharField(
                        help_text="Grade label (e.g., A1, B2, C6 for WASSCE; A, B, C for BECE)",
                        max_length=10,
                    ),
                ),
                (
                    "min_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum percentage for this grade (inclusive)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum percentage for this grade (inclusive)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "aggregate_points",
                    models.IntegerField(
                        blank=True,
                        help_text="Aggregate points for WASSCE/BECE (1-9, where 1 is best)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        help_text="Grade interpretation (e.g., Excellent, Very Good, Credit, Pass, Fail)",
                        max_length=50,
                    ),
                ),
                (
                    "is_pass",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this grade is considered passing",
                    ),
                ),
                (
                    "is_credit",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this grade is a credit pass (relevant for university admission)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scales",
                        to="gradebook.gradingsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Scale",
                "verbose_name_plural": "Grade Scales",
                "db_table": "grade_scale",
                "ordering": ["grading_system", "order", "-min_percentage"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Points earned on this assignment",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="gradebook.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score",
                "verbose_name_plural": "Scores",
                "db_table": "score",
                "ordering": ["student", "assignment"],
            },
        ),
        migrations.CreateModel(
            name="ScoreAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "old_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous score value",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New score value",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_audit_logs",
                        to="gradebook.assignment",
                    ),
                ),
                (
                    "score",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="gradebook.score",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_audit_logs",
                        to="students.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Audit Log",
                "verbose_name_plural": "Score Audit Logs",
                "db_table": "score_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubjectTermGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class work/CA total percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Examination percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total percentage (class + exam)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="Grade label (e.g., A1, B2)", max_length=5
                    ),
                ),
                (
                    "grade_remark",
                    models.CharField(
                        blank=True,
                        help_text="Grade interpretation (e.g., Excellent)",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Class rank for this subject", null=True
                    ),
                ),
                ("teacher_remark", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_grades",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_grades",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_grades",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Term Grade",
                "verbose_name_plural": "Subject Term Grades",
                "db_table": "subject_term_grade",
                "ordering": ["term", "subject", "-total_score"],
            },
        ),
        migrations.CreateModel(
            name="TermReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all subject scores",
                        max_digits=7,
                    ),
                ),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average percentage across all subjects",
                        max_digits=5,
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Overall class position", null=True
                    ),
                ),
                (
                    "out_of",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Total students in class", null=True
                    ),
                ),
                ("subjects_taken", models.PositiveSmallIntegerField(default=0)),
                ("subjects_passed", models.PositiveSmallIntegerField(default=0)),
                ("subjects_failed", models.PositiveSmallIntegerField(default=0)),
                (
                    "aggregate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="WASSCE aggregate (sum of best 6 subject grades, lower is better)",
                        null=True,
                    ),
                ),
                (
                    "credits_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of subjects with credit passes (C6 or better)",
                    ),
                ),
                (
                    "core_subjects_passed",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of core subjects passed"
                    ),
                ),
                (
                    "core_subjects_total",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Total number of core subjects taken"
                    ),
                ),
                ("class_teacher_remark", models.TextField(blank=True)),
                ("head_teacher_remark", models.TextField(blank=True)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "days_present",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of days present in the term",
                        null=True,
                    ),
                ),
                (
                    "days_absent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of days absent in the term",
                        null=True,
                    ),
                ),
                (
                    "total_school_days",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Total school days in the term", null=True
                    ),
                ),
                (
                    "promoted",
                    models.BooleanField(
                        blank=True,
                        help_text="Promotion status (null = not final term)",
                        null=True,
                    ),
                ),
                (
                    "promotion_remarks",
                    models.TextField(
                        blank=True, help_text="Reasons for promotion decision"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promoted_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Class promoted to (if promoted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_students",
                        to="academics.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_reports",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_reports",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Report",
                "verbose_name_plural": "Term Reports",
                "db_table": "term_report",
                "ordering": ["term", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["subject", "term", "assessment_category"],
                name="assignment_subject_82bdc0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("assessment_category", "subject", "term", "name")},
        ),
        migrations.AddIndex(
            model_name="gradescale",
            index=models.Index(
                fields=["grading_system", "min_percentage", "max_percentage"],
                name="grade_scale_grading_8be02a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradescale",
            unique_together={("grading_system", "grade_label")},
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["student", "assignment"], name="score_student_07461c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("student", "assignment")},
        ),
        migrations.AddIndex(
            model_name="scoreauditlog",
            index=models.Index(
                fields=["student", "assignment"], name="score_audit_student_20aae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoreauditlog",
            index=models.Index(
                fields=["user", "created_at"], name="score_audit_user_id_6b52af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoreauditlog",
            index=models.Index(
                fields=["-created_at"], name="score_audit_created_cc1962_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjecttermgrade",
            index=models.Index(
                fields=["student", "term"], name="subject_ter_student_df6cfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjecttermgrade",
            index=models.Index(
                fields=["subject", "term", "total_score"],
                name="subject_ter_subject_6b00e6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjecttermgrade",
            unique_together={("student", "subject", "term")},
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["term", "average"], name="term_report_term_id_5b99ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["term", "aggregate"], name="term_report_term_id_0e5a39_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termreport",
            unique_together={("student", "term")},
        ),
    ]
