# Generated by Django 5.2.9 on 2025-12-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjecttermgrade",
            name="is_passing",
            field=models.BooleanField(
                default=False,
                help_text="Whether this grade is a pass based on grading system",
            ),
        ),
    ]
