# Generated by Django 5.2.9 on 2025-12-27 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_remove_subject_level_fields"),
        ("core", "0004_add_academic_period_type"),
        ("gradebook", "0001_initial"),
        ("students", "0002_add_enrollment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingsystem",
            name="aggregate_subjects_count",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="Number of best subjects used for aggregate calculation (WASSCE: 6)",
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="credit_mark",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Minimum percentage for a credit pass (WASSCE: 50% for C6)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="min_average_for_promotion",
            field=models.DecimalField(
                decimal_places=2,
                default=40.0,
                help_text="Minimum average percentage required for promotion",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="min_subjects_to_pass",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum subjects a student must pass for promotion (0 = use average only)",
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="pass_mark",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Minimum percentage to pass a subject (default 50%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="require_core_pass",
            field=models.BooleanField(
                default=True,
                help_text="Require passing all core subjects for promotion (Ghana standard)",
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="aggregate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="WASSCE aggregate (sum of best 6 subject grades, lower is better)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="core_subjects_passed",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of core subjects passed"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="core_subjects_total",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Total number of core subjects taken"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="credits_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of subjects with credit passes (C6 or better)",
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="days_absent",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Number of days absent in the term", null=True
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="days_present",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Number of days present in the term", null=True
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="promoted_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Class promoted to (if promoted)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_students",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="promotion_remarks",
            field=models.TextField(
                blank=True, help_text="Reasons for promotion decision"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="total_school_days",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Total school days in the term", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["term", "aggregate"], name="term_report_term_id_0e5a39_idx"
            ),
        ),
    ]
