# Generated by Django 5.2.9 on 2025-12-27 07:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0002_ghana_grading_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="points_possible",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Maximum points available for this assignment",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="points",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Points earned on this assignment",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
