# Generated by Django 5.2.9 on 2025-12-28 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        ("gradebook", "0002_add_is_passing_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemarkTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent (80%+)"),
                            ("GOOD", "Good (60-79%)"),
                            ("AVERAGE", "Average (50-59%)"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement (<50%)"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        help_text="Performance category this remark applies to",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Remark text. Use {student_name}, {average}, {position} as placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Remark Template",
                "verbose_name_plural": "Remark Templates",
                "db_table": "remark_template",
                "ordering": ["category", "order"],
            },
        ),
        migrations.AddField(
            model_name="termreport",
            name="attitude_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("VERY_GOOD", "Very Good"),
                    ("GOOD", "Good"),
                    ("FAIR", "Fair"),
                    ("POOR", "Poor"),
                ],
                help_text="Attitude to work",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="class_teacher_signed",
            field=models.BooleanField(
                default=False, help_text="Class teacher has confirmed the remarks"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="class_teacher_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="termreport",
            name="conduct_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Excellent"),
                    ("B", "Very Good"),
                    ("C", "Good"),
                    ("D", "Fair"),
                    ("E", "Poor"),
                ],
                help_text="Overall conduct grade (A-E)",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="head_teacher_approved",
            field=models.BooleanField(
                default=False, help_text="Head teacher has approved the report"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="head_teacher_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="termreport",
            name="interest_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("VERY_GOOD", "Very Good"),
                    ("GOOD", "Good"),
                    ("FAIR", "Fair"),
                    ("POOR", "Poor"),
                ],
                help_text="Interest in school activities",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="punctuality_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("VERY_GOOD", "Very Good"),
                    ("GOOD", "Good"),
                    ("FAIR", "Fair"),
                    ("POOR", "Poor"),
                ],
                help_text="Punctuality record",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ReportDistributionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email with PDF"),
                            ("SMS", "SMS Summary"),
                            ("BOTH", "Email and SMS"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("email_sent_to", models.EmailField(blank=True, max_length=254)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_error", models.TextField(blank=True)),
                (
                    "sms_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sms_sent_to", models.CharField(blank=True, max_length=20)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sms_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sms_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_distributions",
                        to="communications.smsmessage",
                    ),
                ),
                (
                    "term_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_logs",
                        to="gradebook.termreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Distribution Log",
                "verbose_name_plural": "Report Distribution Logs",
                "db_table": "report_distribution_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["term_report", "-created_at"],
                        name="report_dist_term_re_c90cbd_idx",
                    ),
                    models.Index(
                        fields=["email_status"], name="report_dist_email_s_c0c2fd_idx"
                    ),
                    models.Index(
                        fields=["sms_status"], name="report_dist_sms_sta_90934b_idx"
                    ),
                ],
            },
        ),
    ]
