# Generated by Django 5.2.9 on 2025-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_add_student_subject_enrollment"),
        ("core", "0001_initial"),
        ("gradebook", "0003_add_remarks_and_distribution"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("CLASS_SCORE", "Class Score / Continuous Assessment"),
                    ("EXAM", "Examination / Final Exam"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Type of category for grade calculation",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="remarktemplate",
            index=models.Index(
                fields=["is_active", "category"], name="remark_temp_is_acti_718055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjecttermgrade",
            index=models.Index(
                fields=["is_passing"], name="subject_ter_is_pass_7808d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["term", "position"], name="term_report_term_id_3f9d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["student", "term"], name="term_report_student_bc7d0d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("percentage__gte", 0), ("percentage__lte", 100)),
                name="assessment_category_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("points_possible__gt", 0)),
                name="assignment_points_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradescale",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_percentage__lte", models.F("max_percentage"))),
                name="grade_scale_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradescale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_percentage__gte", 0), ("min_percentage__lte", 100)
                ),
                name="grade_scale_min_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradescale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_percentage__gte", 0), ("max_percentage__lte", 100)
                ),
                name="grade_scale_max_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gte", 0)), name="score_points_non_negative"
            ),
        ),
    ]
