# Generated by Django 5.2.9 on 2025-12-27 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0003_decimal_scores"),
        ("students", "0002_add_enrollment_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "old_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous score value",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New score value",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_audit_logs",
                        to="gradebook.assignment",
                    ),
                ),
                (
                    "score",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="gradebook.score",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_audit_logs",
                        to="students.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Audit Log",
                "verbose_name_plural": "Score Audit Logs",
                "db_table": "score_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "assignment"],
                        name="score_audit_student_20aae6_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="score_audit_user_id_6b52af_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="score_audit_created_cc1962_idx"
                    ),
                ],
            },
        ),
    ]
