# Generated by Django 5.2.9 on 2025-12-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0004_add_database_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjecttermgrade",
            name="category_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Scores for each assessment category (supports multiple categories)",
            ),
        ),
        migrations.AlterField(
            model_name="subjecttermgrade",
            name="class_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Class work/CA total percentage (legacy, for standard 2-category system)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subjecttermgrade",
            name="exam_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Examination percentage (legacy, for standard 2-category system)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subjecttermgrade",
            name="total_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total percentage (sum of all category scores)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
