# Generated by Django 5.2.9 on 2026-01-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0006_make_assignment_date_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcategory",
            name="expected_assessments",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Recommended number of assessments per term (0 = no recommendation)",
            ),
        ),
        migrations.AddField(
            model_name="assessmentcategory",
            name="max_assessments",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Maximum allowed assessments per term (0 = no maximum)",
            ),
        ),
        migrations.AddField(
            model_name="assessmentcategory",
            name="min_assessments",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum required assessments per term (0 = no minimum)",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date/time the assignment was recorded in the system",
            ),
        ),
    ]
