# Generated by Django 5.2.9 on 2026-02-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0007_add_assessment_count_advisory_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="termreport",
            old_name="punctuality_rating",
            new_name="attendance_rating",
        ),
    ]
