# Generated by Django 5.2.9 on 2026-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0008_rename_punctuality_to_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termreport",
            name="attendance_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("VERY_GOOD", "Very Good"),
                    ("GOOD", "Good"),
                    ("FAIR", "Fair"),
                    ("POOR", "Poor"),
                ],
                help_text="Attendance rating",
                max_length=10,
            ),
        ),
    ]
