# Generated by Django 5.2.9 on 2026-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0010_fix_grade_scale_gaps_add_times_late"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="score",
            name="score_student_07461c_idx",
        ),
    ]
