# Generated by Django 5.2.9 on 2026-03-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0011_remove_score_score_student_07461c_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termreport",
            name="attitude_rating",
            field=models.CharField(
                blank=True, help_text="Attitude to work (free text)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="termreport",
            name="conduct_rating",
            field=models.CharField(
                blank=True, help_text="Overall conduct (free text)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="termreport",
            name="interest_rating",
            field=models.CharField(
                blank=True,
                help_text="Interest in school activities (free text)",
                max_length=100,
            ),
        ),
    ]
