# Generated by Django 5.2.9 on 2026-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0012_change_conduct_attitude_interest_to_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="feedback",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional teacher feedback for this score",
                max_length=200,
            ),
        ),
    ]
