# Generated by Django 5.2.9 on 2026-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0016_remove_termreport_attendance_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="termreport",
            name="days_excused",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of valid school days the student was excused",
                null=True,
            ),
        ),
    ]
