# Generated by Django 5.2.9 on 2026-08-08 11:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_max_assessments_to_one(apps, schema_editor):
    """
    Enforcement of max_assessments (single-vs-multiple-assignments-per-
    category) didn't exist before this migration, so max_assessments=0
    ("no maximum") on an existing category just meant "nobody set this
    field" rather than a deliberate choice to allow unlimited assignments.
    Backfilling those to 1 makes "one assignment per category" the actual
    starting behavior everywhere, not just for categories created after
    this point. A category an admin had already set to something other
    than 0 is left alone - that was a deliberate choice.

    Only categories that were never actually used for more than one
    assignment in the same subject/term get backfilled, though - a category
    with a documented history of 2+ assignments per subject/term was clearly
    already being used as "unlimited" in practice, so capping it
    retroactively would lock out real, already-recorded usage (new
    assignments in that category would start failing with no indication why).
    """
    AssessmentCategory = apps.get_model('gradebook', 'AssessmentCategory')
    Assignment = apps.get_model('gradebook', 'Assignment')

    for category in AssessmentCategory.objects.filter(max_assessments=0):
        busiest = (
            Assignment.objects.filter(assessment_category=category)
            .values('subject_id', 'term_id')
            .annotate(count=models.Count('id'))
            .order_by('-count')
            .values_list('count', flat=True)
            .first()
        ) or 0
        if busiest <= 1:
            category.max_assessments = 1
            category.save(update_fields=['max_assessments'])


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0017_termreport_days_excused"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcategory",
            name="default_max_marks",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default maximum marks for new assignments in this category. Pre-fills the marks field when a teacher creates an assignment, but can still be overridden per assignment. Leave blank to require teachers to enter it manually every time.",
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(Decimal("9999")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assessmentcategory",
            name="max_assessments",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Maximum allowed assessments per subject per term (0 = no maximum). Defaults to 1 (one assignment per category) - raise it for a category a school wants to allow multiple assignments in, e.g. several small quizzes under "Class Score".',
            ),
        ),
        migrations.RunPython(backfill_max_assessments_to_one, migrations.RunPython.noop),
    ]
