# Generated by Django 5.2.9 on 2026-01-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="education_system",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Only (Creche - Basic 9)"),
                    ("shs", "SHS Only"),
                    ("both", "Both Basic and SHS"),
                ],
                default="both",
                help_text="Determines which educational levels and features are available",
                max_length=10,
            ),
        ),
    ]
