# Generated by Django 5.2.9 on 2025-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for sidebar display', max_length=20),
        ),
    ]
