# Generated by Django 5.2.9 on 2026-01-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_add_education_system_to_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="region",
        ),
        migrations.AddField(
            model_name="school",
            name="location_district",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the district within the region",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="schools.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="location_region",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the region where the school is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="schools.region",
                verbose_name="Region",
            ),
        ),
    ]
