# Generated by Django 5.2.9 on 2025-12-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_school_address_school_city_school_digital_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="school",
            name="motto",
        ),
    ]
