# Generated by Django 5.2.9 on 2026-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_add_region_district_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="enabled_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Specific levels offered (e.g., ['basic', 'shs']). If empty, defaults based on education_system.",
            ),
        ),
    ]
