# Generated by Django 5.2.9 on 2026-01-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_add_enabled_levels_to_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive schools cannot be accessed"
            ),
        ),
    ]
