# Generated by Django 5.2.9 on 2026-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_add_is_active_to_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="accent_color",
            field=models.CharField(
                default="#F59E0B",
                help_text="Accent/highlight color (hex)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="accent_color_oklch",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="school",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Browser tab icon",
                null=True,
                upload_to="school_favicons/",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="School logo/crest",
                null=True,
                upload_to="school_logos/",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="motto",
            field=models.CharField(
                blank=True, help_text="School motto", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="primary_color",
            field=models.CharField(
                default="#4F46E5", help_text="Main brand color (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="primary_color_oklch",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="school",
            name="secondary_color",
            field=models.CharField(
                default="#7C3AED", help_text="Secondary brand color (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="secondary_color_oklch",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
