# Generated by Django 5.2.9 on 2026-02-01 08:29

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_add_branding_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Browser tab icon",
                null=True,
                storage=core.storage.PublicSchemaStorage(),
                upload_to="school_favicons/",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="School logo/crest",
                null=True,
                storage=core.storage.PublicSchemaStorage(),
                upload_to="school_logos/",
            ),
        ),
    ]
