# Generated by Django 5.2.9 on 2026-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_use_public_storage_for_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="motto",
            field=models.CharField(help_text="School motto", max_length=200),
        ),
        migrations.AlterField(
            model_name="school",
            name="short_name",
            field=models.CharField(
                help_text="Short name for sidebar display", max_length=20
            ),
        ),
    ]
