# Generated by Django 5.2.9 on 2026-02-22 05:56

import core.storage
import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_make_short_name_motto_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="favicon",
            field=models.FileField(
                blank=True,
                help_text="Browser tab icon (PNG, JPG, WebP, SVG)",
                null=True,
                storage=core.storage.PublicSchemaStorage(),
                upload_to="school_favicons/",
                validators=[schools.models.validate_image_or_svg],
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="School logo/crest (PNG, JPG, WebP, SVG)",
                null=True,
                storage=core.storage.PublicSchemaStorage(),
                upload_to="school_logos/",
                validators=[schools.models.validate_image_or_svg],
            ),
        ),
    ]
