# Generated by Django 5.2.9 on 2026-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_allow_svg_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="motto",
            field=models.CharField(help_text="School motto or slogan", max_length=200),
        ),
    ]
