# Generated by Django 5.2.9 on 2026-03-16 21:38

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_alter_school_motto"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="headmaster_signature",
            field=models.ImageField(
                blank=True,
                help_text="Headmaster's signature image (PNG, JPG, WebP) for report cards",
                null=True,
                storage=core.storage.PublicSchemaStorage(),
                upload_to="school_signatures/",
            ),
        ),
    ]
