# Generated by Django 5.2.9 on 2025-12-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., General Arts, Business, Science",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., ART, BUS, SCI", max_length=10, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Mathematics, English Language, Integrated Science",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="e.g., MATH, ENG, INT SCI", max_length=20
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="Optional subject code", max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_core",
                    models.BooleanField(
                        default=True, help_text="Core subjects are mandatory"
                    ),
                ),
                ("for_kg", models.BooleanField(default=False, verbose_name="KG")),
                (
                    "for_primary",
                    models.BooleanField(default=True, verbose_name="Primary"),
                ),
                ("for_jhs", models.BooleanField(default=True, verbose_name="JHS")),
                ("for_shs", models.BooleanField(default=False, verbose_name="SHS")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programmes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="For SHS electives: which programmes offer this subject",
                        related_name="subjects",
                        to="academics.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["-is_core", "name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("kg", "Kindergarten"),
                            ("primary", "Primary"),
                            ("jhs", "JHS"),
                            ("shs", "SHS"),
                        ],
                        default="primary",
                        max_length=10,
                    ),
                ),
                (
                    "level_number",
                    models.PositiveSmallIntegerField(help_text="1, 2, 3, etc."),
                ),
                ("section", models.CharField(help_text="A, B, C, etc.", max_length=5)),
                (
                    "name",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: B1-A, JHS2-B, 1ART-A",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=35, help_text="Maximum number of students"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for SHS only",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="academics.programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["level_type", "level_number", "programme", "section"],
                "unique_together": {
                    ("level_type", "level_number", "programme", "section")
                },
            },
        ),
    ]
