# Generated by Django 5.2.9 on 2025-12-28 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("L", "Late"),
                            ("E", "Excused"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "session_type",
                    models.CharField(
                        choices=[("Daily", "Daily Register")],
                        default="Daily",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("kg", "Kindergarten"),
                            ("primary", "Primary"),
                            ("jhs", "JHS"),
                            ("shs", "SHS"),
                        ],
                        default="primary",
                        max_length=10,
                    ),
                ),
                (
                    "level_number",
                    models.PositiveSmallIntegerField(help_text="1, 2, 3, etc."),
                ),
                ("section", models.CharField(help_text="A, B, C, etc.", max_length=5)),
                (
                    "name",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: B1-A, JHS2-B, 1ART-A",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=35, help_text="Maximum number of students"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["level_type", "level_number", "programme", "section"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periods_per_week", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Subject Allocation",
                "verbose_name_plural": "Subject Allocations",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Period 1, Morning Assembly, Break",
                        max_length=50,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order in timetable"
                    ),
                ),
                (
                    "is_break",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a break period (not for classes)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., General Arts, Business, Science",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., ART, BUS, SCI", max_length=10, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Mathematics, English Language, Integrated Science",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="e.g., MATH, ENG, INT SCI", max_length=20
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="Optional subject code", max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_core",
                    models.BooleanField(
                        default=True, help_text="Core subjects are mandatory"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["-is_core", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "ordering": ["weekday", "period__order"],
            },
        ),
    ]
