# Generated by Django 5.2.9 on 2025-12-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="academics.attendancesession",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="The form tutor or class teacher responsible for this class.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_classes",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_sessions",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_assignments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for SHS only",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academics.programme",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="programmes",
            field=models.ManyToManyField(
                blank=True,
                help_text="For SHS electives: which programmes offer this subject",
                related_name="subjects",
                to="academics.programme",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_allocations",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="class_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.classsubject",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.period",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together={("class_assigned", "date", "session_type")},
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("level_type", "level_number", "programme", "section")},
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_assigned", "subject")},
        ),
    ]
