# Generated by Django 5.2.9 on 2025-12-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="The form tutor or class teacher responsible for this class.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_classes",
                to="teachers.teacher",
            ),
        ),
    ]
