# Generated by Django 5.2.9 on 2025-12-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="is_double",
            field=models.BooleanField(
                default=False,
                help_text="If true, this lesson spans two consecutive periods",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="period",
            field=models.ForeignKey(
                help_text="Starting period for this lesson",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.period",
            ),
        ),
    ]
