# Generated by Django 5.2.9 on 2025-12-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_attendancesession_attendancerecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="for_jhs",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="for_kg",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="for_primary",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="for_shs",
        ),
    ]
