# Generated by Django 5.2.9 on 2026-01-01 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_add_student_subject_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Room 101, Science Lab 1", max_length=50
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short code e.g., R101, LAB1",
                        max_length=10,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40, help_text="Maximum seating capacity"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Classroom"),
                            ("lab", "Laboratory"),
                            ("computer", "Computer Lab"),
                            ("library", "Library"),
                            ("hall", "Assembly Hall"),
                            ("other", "Other"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical room where this lesson is held",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_entries",
                to="academics.classroom",
            ),
        ),
    ]
