# Generated by Django 5.2.9 on 2026-01-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_add_classroom_model"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["weekday", "period"], name="timetable_weekday_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["class_subject", "period", "weekday"],
                name="timetable_conflict_check_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(fields=["weekday"], name="timetable_weekday_idx"),
        ),
    ]
