# Generated by Django 5.2.9 on 2026-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_timetable_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='e.g., Room 101, Science Lab 1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(help_text='e.g., Period 1, Morning Assembly, Break', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='e.g., Mathematics, English Language, Integrated Science', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(help_text='e.g., MATH, ENG, INT SCI', max_length=20, unique=True),
        ),
    ]
