# Generated by Django 5.2.9 on 2026-01-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_add_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level_type',
            field=models.CharField(choices=[('creche', 'Creche'), ('kg', 'Kindergarten'), ('primary', 'Primary'), ('jhs', 'JHS'), ('shs', 'SHS')], default='primary', max_length=10),
        ),
    ]
