# Generated by Django 5.2.9 on 2026-01-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_add_creche_level_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(help_text='A, B, C or Red, Blue, Green, etc.', max_length=15),
        ),
    ]
