# Generated by Django 5.2.9 on 2026-01-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_increase_section_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='', help_text='A, B, C or Red, Blue, Green, etc. (Optional)', max_length=15),
        ),
    ]
