# Generated by Django 5.2.9 on 2026-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_convert_primary_jhs_to_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level_type',
            field=models.CharField(choices=[('creche', 'Creche'), ('nursery', 'Nursery'), ('kg', 'Kindergarten'), ('basic', 'Basic'), ('shs', 'SHS')], default='basic', max_length=10),
        ),
    ]
