# Generated by Django 5.2.9 on 2026-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0014_add_missing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="required_electives",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Minimum number of elective subjects students must take (typically 3-4 for SHS)",
            ),
        ),
    ]
