# Generated by Django 5.2.9 on 2026-01-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0015_add_required_electives_to_programme"),
        ("teachers", "0004_add_missing_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="class_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="The subject for this lesson attendance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_sessions",
                to="academics.classsubject",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="The period during which attendance was taken",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_sessions",
                to="academics.period",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="timetable_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific timetable slot for this attendance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_sessions",
                to="academics.timetableentry",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="attendance_type",
            field=models.CharField(
                choices=[("daily", "Daily Register"), ("per_lesson", "Per-Lesson")],
                default="daily",
                help_text="Daily: one register per day. Per-Lesson: each teacher marks their lesson.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily Register"),
                    ("Lesson", "Per-Lesson Attendance"),
                ],
                default="Daily",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["timetable_entry", "date"], name="attsess_entry_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["class_subject", "date"], name="attsess_subj_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_type", "Daily")),
                fields=("class_assigned", "date"),
                name="unique_daily_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_type", "Lesson")),
                fields=("class_assigned", "date", "timetable_entry"),
                name="unique_lesson_session",
            ),
        ),
    ]
