# Generated by Django 5.2.9 on 2026-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0016_alter_attendancesession_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Basic 1-3 Core Subjects, SHS Science Core",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of when to use this template",
                    ),
                ),
                (
                    "level_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Level types this template applies to (empty = all levels)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        help_text="Subjects included in this template",
                        related_name="templates",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Template",
                "verbose_name_plural": "Subject Templates",
                "ordering": ["name"],
            },
        ),
    ]
