# Generated by Django 5.2.9 on 2026-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0017_add_subject_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjecttemplate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subjecttemplate",
            name="level_types",
        ),
        migrations.AlterField(
            model_name="subjecttemplate",
            name="name",
            field=models.CharField(
                help_text="e.g., Core Subjects, Science Electives",
                max_length=100,
                unique=True,
            ),
        ),
    ]
