# Generated by Django 5.2.9 on 2026-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0018_remove_template_level_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="auto_enroll",
            field=models.BooleanField(
                default=True,
                help_text="Automatically enroll all students in this subject",
            ),
        ),
    ]
