# Generated by Django 5.2.9 on 2026-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0019_add_auto_enroll_to_classsubject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjecttemplate",
            options={
                "ordering": ["-is_default", "name"],
                "verbose_name": "Subject Template",
                "verbose_name_plural": "Subject Templates",
            },
        ),
        migrations.AddField(
            model_name="subjecttemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Default templates are pre-selected when applying to matching classes",
            ),
        ),
        migrations.AddField(
            model_name="subjecttemplate",
            name="level_type",
            field=models.CharField(
                choices=[
                    ("all", "All Levels"),
                    ("primary", "Primary (KG, Basic 1-6)"),
                    ("jhs", "JHS (Basic 7-9)"),
                    ("shs", "SHS"),
                ],
                default="all",
                help_text="Filter templates by level when applying to classes",
                max_length=10,
            ),
        ),
    ]
