# Generated by Django 5.2.9 on 2026-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0020_add_level_type_to_subject_template"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attrec_sess_stud_idx",
        ),
    ]
