# Generated by Django 5.2.9 on 2026-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0021_remove_attendancerecord_attrec_sess_stud_idx"),
        ("teachers", "0010_remove_redundant_db_index_on_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                condition=models.Q(("programme__isnull", False)),
                fields=("level_type", "level_number", "programme", "section"),
                name="unique_class_with_programme",
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                condition=models.Q(("programme__isnull", True)),
                fields=("level_type", "level_number", "section"),
                name="unique_class_without_programme",
            ),
        ),
    ]
