# Generated by Django 5.2.9 on 2026-03-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0022_alter_class_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="marked_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last marked this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
