# Generated by Django 5.2.9 on 2026-03-15 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0023_add_attendance_audit_fields"),
        ("students", "0025_add_guardian_notification_pref"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceExcuse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("illness", "Illness"),
                            ("family", "Family Emergency"),
                            ("medical", "Medical Appointment"),
                            ("travel", "Travel"),
                            ("religious", "Religious Observance"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the absence",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_excuses",
                        to="students.student",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="academics_a_student_b566a8_idx",
                    ),
                    models.Index(
                        fields=["date_from", "date_to"],
                        name="academics_a_date_fr_289686_idx",
                    ),
                ],
            },
        ),
    ]
